language: node_js
os: osx
node_js:
  - "12"
addons:
  apt:
    packages:
      - xvfb
branches:
  only:
    - master
    - develop
    - "/^v.*$/"
before_script:
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    edge: true
    skip_cleanup: true
    api_key:
      secure: PCL6FS8GDmgiTFhZ8rPmCgrktRYYT7QV/yyVLZk93J6WTAI5ChbtFusB+O6cyia0+G7CEmNZXwc6OGGs6iXCFAckP2lMqexfeTU35pd0feeN+gcvVdXudUo+FVVkgb2FPBUjj0RvanL6RvuoZHeUFIrTho4VK6gtlm8ErmAA/JZhhRACSI2cwV5GoJQtUl1i0D7KiA/w5AhtMGKhG2kc26MPXF3k715XcO+qpt1M6lK6uu0wonLk3EgH2YqndY4OPoffneQVbL1jwnkCoY4NRyuaQeHjNeUSvxI7QG4c95kFg6XcnCpi9Kqu2o6wZpxIIMlSjYi0C9nja+scdwjaEc/nGO0WTNC/UFbAgK36EkoxFcIaZiDq/dhtNekyDzHmJklrI6iEBMa7Fb3y1PE1dK+FBeHq3G3aVWFRYExZtpKyq16Cj7+588qalOYfgib0WT/EWg9e4vqM2vdw2ALm9gYwM9WJSgVVTRarm1nL4G/2aamCly5zxC9gKzNF6ikxG5cTYHypNZppOaZZ8+iKUYso9VOiGsW6GRXTLxY0oGF+7DU8In5CqxgP/Q6F2BWWKo1cUoFuzqQZ1ixeaq6MehS01CF5JXhrKaN1TTMFAIBizRQnE3pibyGz+Sgms8XtQ0wedS9yXr57joCC5rr6yILzmw9UhUIPdd2p/FbTYr0=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/regl-scatterplot
  - provider: npm
    edge: true
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: o5a+jhH6XPPpa7FGEEly1gq215u5WOGx8SUr1dT/y7I+cAONACvZnYyehW35YhjqYVaMWm5x9DbfE29bpgoz78alzDrLaCqqZ0HB49J1XsLVXLL3Qvm262Irw6Yg87TuSkt2BsTKei2kynj2+b89aWhkUUC3jsxadok2YTkMNfzUcFwH8MfApxFXZ13Icw/T92Am2YERAj5kEYMFPvYutngrw3ds9jsBt7sjltF6N21MqtDN9jyKt9goxk0L7ne4AwdkUCtQQJo+VOIAuUA9W96bQxDzagFWRvUHuUmJBr3IpsGrwRR5beWDDycfjJkP/u6iqawXAuEUbK2q0qBgC4XCjz8NILBcgNZfh+UYAIc+5mVlVCGVJtQ0wgf/7gGbQScSQ+qCA5Hc+BvDWeKy2661J/L1trt/nT+PQjSNuEuT2vllQHQrZOdWkwRIzxDeaTRIqdSNBpCpJi11bpjd//LJn70cooTQVEJPozuJ4NjiAgJQQ8l1jgzn6QJwbpL+WdKNgTt4Bn9J6pHjCKw6c/dEnEj3n3gRP+tuXHR7GHd6ilunGS/00BxWEwSykKc7emVqff/eQNDf4wboiusR1fkMy7X6m1obXxISzAhtTn+x6z26BRLX84WDikvX5YXpb7DaPCg2ri70ebAfxsc5VN8F9m3h9CFaxZyITDSh0FU=
    on:
      branch: master
      tags: true
      repo: flekschas/regl-scatterplot
